---
### -O forces scp versus sftp which Cisco IOS does support
- name: Copy file over to flash on network device
  ansible.builtin.shell: >
    scp -O -o StrictHostKeyChecking=no
    /tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt
    {{ ansible_user }}@{{ inventory_hostname }}:'flash:{{ rollback_date }}-{{ inventory_hostname }}.txt'
  delegate_to: backup-server
  run_once: true


- name: Overwrite startup config - archive
  cisco.ios.ios_config:
    lines:
      - 'archive'

- name: Overwrite startup config - overwrite
  cisco.ios.ios_command:
    commands:
      - command: 'configure replace flash://{{ rollback_date }}-{{ inventory_hostname }}.txt force'
