---
- name: Retrieve network configurations
  hosts: all
  gather_facts: false

  tasks:

    - name: Merge JUNOS acl
      junipernetworks.junos.junos_acls:
        config:
          - afi: ipv4
            acls:
              - name: "{{ ansible_configured_acl | default('ansible_configured_acl') }}"
                aces:
                  - name: "{{ ansible_configured_term | default('ansible_configured_term') }}"
                    destination:
                      port_protocol:
                        eq: "{{ ansible_configured_protocol | default('ssh') }}"
                    protocol: tcp
                    grant: "{{ ansible_grant_status | default('permit') }}"
        state: merged
