---
- name: Retrieve network configurations
  hosts: network
  gather_facts: false

  tasks:

    - name: Merge JUNOS acl
      junipernetworks.junos.junos_acls:
        config:
          - afi: ipv4
            acls:
              - name: allow_ssh_acl
                aces:
                  - name: ssh_rule
                    source:
                      port_protocol:
                        eq: ssh
                    protocol: tcp
        state: merged
